# Generated by Django 4.2.5 on 2023-09-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='prof_pic/')),
                ('email', models.EmailField(max_length=20)),
                ('phone_number', models.TextField(max_length=14)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=10)),
                ('address', models.TextField(max_length=40)),
                ('religions', models.CharField(choices=[('Islam', 'Islam'), ('HIndu', 'HIndu'), ('Others', 'Others')], default='Islam', max_length=10)),
                ('blood_groop', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='o+', max_length=10)),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
